### ISSUE TITLE
Create Tea List

### ISSUE THREAD

**Issue by annettevogt** [annettevogt/capstone-project#1]
## Value statement
 
As a **tea fan**
I need **a list of teas with some detail information and tea description**
so that **I get an overview about my favorite teas and how each tea tastes**

## Description (Text, Scribble, Wireframe, Design)
 
![scribble1](https://user-images.githubusercontent.com/65187965/86350141-899ff580-bc62-11ea-86bb-51e5859b6988.jpg)

* It's a scrolling list of teas with details where the tea was bought and tasting description
* Every list item contains tea name, detail and description

 
## Acceptance criteria

* [ ]  List items and details are scrolled vertically
* [ ]  Header is always visible

## Tasks

* [ ]  Create feature branch
* [ ]  Create component (Tea item) in Storybook
* [ ]  Write component tests
* [ ]  Add components to app
* [ ]  Add missing styles

## Size
medium
