### ISSUE TITLE
Add tasting description and button back

### ISSUE THREAD

**Issue by annettevogt** [annettevogt/capstone-project#3]
## Value statement
 
As a **tea fan**
I need **a description of each tea**
so that **I know how each tea tastes**

## Description (Text, Scribble, Wireframe, Design)
 
* The tasting description belongs to each tea list item as a field
* Every tea description contains a headline and the description itself in text form
* The tasting description is scrollable, together with the information tea item
 
## Acceptance criteria

* [ ]  Tasting descriptions are simple text in a good readable size
* [ ]  All tasting descriptions are always visible
* [ ]  Tasting descriptions are scrolled vertically
* [ ]  If no tasting description is given no description field is shown
* [ ]  If no tasting description is given no button back is shown

![seite_2a](https://user-images.githubusercontent.com/65187965/86237560-454a2200-bb9c-11ea-8a96-8fe40056cc54.jpg)

## Tasks

for example
* [ ]  Create feature branch
* [ ]  Create components (add components) in Storybook
* [ ]  Write component tests
* [ ]  Add components to app (feature implementation with state)
* [ ]  Add missing styles
* [ ]  Write integration tests w/ Cypress
