### ISSUE TITLE
Add Input Field and Submit Button

### ISSUE THREAD

**Issue by annettevogt** [annettevogt/capstone-project#4]
## Value statement
 
As a **tea fan**
I need **an input field**
so that **I can add further favorite teas, its details and tasting description**

## Description (Text, Scribble, Wireframe, Design)
 
* It has a simple headline
* Via a button back you can leave the input mask and get back to the overview of favorite teas
* It has 3 input fields: name, bought here, tasting description
 

## Acceptance criteria

* [ ]  The input fields have to be visually separated
* [ ]  Tea names, its detail and the tasting description are simple text in a good readable size
* [ ]  All input fields are always visible
* [ ]  The field of the tasting description is adjustible for more space
* [ ]  Maximal number of characters is 300
* [ ]  The input mask is scrolled vertically, if the tasting description field becomes bigger than the screen
* [ ]  Name and buy details are required, the tasting description is optional
* [ ]  Header is always visible
* [ ]  Button back is always visible

![issue_3](https://user-images.githubusercontent.com/65187965/86282298-3f296500-bbdf-11ea-8529-5a5f0ee449aa.jpg)

## Tasks

* [ ]  Create feature branch
* [ ]  Create components (input fields, submit button) in Storybook
* [ ]  Write component tests
* [ ]  Add components to app (feature implementation with state)
* [ ]  Add missing styles
* [ ]  Write integration tests with Cypress
