### ISSUE TITLE
Add Add Button

### ISSUE THREAD

**Issue by annettevogt** [annettevogt/capstone-project#5]
## Value statement
 
As a **tea fan**
I need **to add further favorite teas**
so that **I can collect them**

## Description (Text, Scribble, Wireframe, Design)
 
* It's an add button at the bottom of the entrance information and description page
* The button leads to the input page
 

## Acceptance criteria

* [ ]  The add button is an item of the navigation list
* [ ]  The button is always visible
* [ ]  The button is fixed at its position at the bottom navigation of the page
* [ ]  The vertically scrolled content disappears behind the button

![issue_4_1](https://user-images.githubusercontent.com/65187965/86284919-063fbf00-bbe4-11ea-8059-2de0d8b5ab50.jpg)
![issue_4_2](https://user-images.githubusercontent.com/65187965/86284922-0770ec00-bbe4-11ea-9f10-1594f8568fa3.jpg)

## Tasks

* [ ]  Create feature branch
* [ ]  Create component (add button) in Storybook
* [ ]  Write component tests
* [ ]  Add components to app (feature implementation with state)
* [ ]  Add missing styles
* [ ]  Write integration tests with Cypress
