### ISSUE TITLE
Save State locally

### ISSUE THREAD

**Issue by annettevogt** [annettevogt/capstone-project#6]
## Value statement
 
As a **tea fan**
I need **local storage**
so that **I can save my appended favorite teas**

## Description (Text, Scribble, Wireframe, Design)
 
* No visible impact
 
## Acceptance criteria

* [ ]  Every change on the state input should trigger a save to localStorage
* [ ]  Reload of the page should load appended teas from localStorage

## Tasks

* [ ]  Create services for localStorage
* [ ]  Implement save/load for new tea items
* [ ]  Write component tests
* [ ]  Add components to app (feature implementation with state)
* [ ]  Add missing styles
* [ ]  Write integration tests with Cypress
