### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by annettevogt** [annettevogt/capstone-project#7]
## Tasks
 

* [ ]  
* [ ]  
* [ ]  
* [ ]  
* [ ]  

## Tasks

for example
* [ ]  Create feature branch
* [ ]  Create components (add components) in Storybook
* [ ]  Write component tests
* [ ]  Add components to app (feature implementation with state)
* [ ]  Add missing styles
* [ ]  Write integration tests w/ Cypress
